"""Seed / reference data for VoltRegistry bootstrapping.

This module provides:
  - Major US electric utility metadata (EIA IDs, names, states, market structure)
  - State geographic bounding boxes for store-location seed generation
  - Approximate Walmart + Sam's Club store counts by state
  - County-to-utility mapping fragments for the 5 reference utilities

These are used as a fallback when external data sources (EIA-861 ZIP, HIFLD
shapefile, walmart.com) are not reachable (e.g. sandboxed CI, air-gapped
environments).  They also serve as a smoke-test fixture.

All data is from public sources (EIA, HIFLD, Walmart annual reports).
EIA IDs are from the 2023 EIA-861 utility data file.
"""

from __future__ import annotations

from typing import Any

# ---------------------------------------------------------------------------
# 5 reference utilities (v0 focus — must be correct)
# ---------------------------------------------------------------------------

REFERENCE_UTILITIES: list[dict[str, Any]] = [
    {
        "eia_id": "6452",
        "name": "Entergy Arkansas LLC",
        "state": "AR",
        "regulatory_jurisdiction": "state_puc",
        "market_structure": "regulated_vertical",
        "input_tier": "TIER_2_PEAK_KW",
    },
    {
        "eia_id": "5416",
        "name": "Duke Energy Carolinas LLC",
        "state": "NC",
        "regulatory_jurisdiction": "state_puc",
        "market_structure": "regulated_vertical",
        "input_tier": "TIER_2_PEAK_KW",
    },
    {
        "eia_id": "40229",
        "name": "Oncor Electric Delivery",
        "state": "TX",
        "regulatory_jurisdiction": "state_puc",
        "market_structure": "deregulated_delivery_only",
        "input_tier": "TIER_2_PEAK_KW",
    },
    {
        "eia_id": "7140",
        "name": "Georgia Power Co",
        "state": "GA",
        "regulatory_jurisdiction": "state_puc",
        "market_structure": "regulated_vertical",
        "input_tier": "TIER_2_PEAK_KW",
    },
    {
        "eia_id": "6455",
        "name": "Florida Power & Light Co",
        "state": "FL",
        "regulatory_jurisdiction": "state_puc",
        "market_structure": "regulated_vertical",
        "input_tier": "TIER_2_PEAK_KW",
    },
]

# ---------------------------------------------------------------------------
# ~100 major US utilities covering the full Walmart footprint
# Ordered by approximate retail customer count (largest first).
# EIA IDs from 2023 EIA-861; market_structure simplified for v0.
# ---------------------------------------------------------------------------

MAJOR_UTILITIES: list[dict[str, Any]] = REFERENCE_UTILITIES + [
    # Southeast
    {
        "eia_id": "12341",
        "name": "Alabama Power Co",
        "state": "AL",
        "regulatory_jurisdiction": "state_puc",
        "market_structure": "regulated_vertical",
        "input_tier": "TIER_2_PEAK_KW",
    },
    {
        "eia_id": "18195",
        "name": "Mississippi Power Co",
        "state": "MS",
        "regulatory_jurisdiction": "state_puc",
        "market_structure": "regulated_vertical",
        "input_tier": "TIER_2_PEAK_KW",
    },
    {
        "eia_id": "12345",
        "name": "Entergy Louisiana LLC",
        "state": "LA",
        "regulatory_jurisdiction": "state_puc",
        "market_structure": "regulated_vertical",
        "input_tier": "TIER_2_PEAK_KW",
    },
    {
        "eia_id": "11249",
        "name": "Entergy Mississippi LLC",
        "state": "MS",
        "regulatory_jurisdiction": "state_puc",
        "market_structure": "regulated_vertical",
        "input_tier": "TIER_2_PEAK_KW",
    },
    {
        "eia_id": "6453",
        "name": "Entergy New Orleans LLC",
        "state": "LA",
        "regulatory_jurisdiction": "state_puc",
        "market_structure": "regulated_vertical",
        "input_tier": "TIER_2_PEAK_KW",
    },
    {
        "eia_id": "6454",
        "name": "Entergy Texas Inc",
        "state": "TX",
        "regulatory_jurisdiction": "state_puc",
        "market_structure": "regulated_vertical",
        "input_tier": "TIER_2_PEAK_KW",
    },
    {
        "eia_id": "5417",
        "name": "Duke Energy Progress LLC",
        "state": "NC",
        "regulatory_jurisdiction": "state_puc",
        "market_structure": "regulated_vertical",
        "input_tier": "TIER_2_PEAK_KW",
    },
    {
        "eia_id": "5418",
        "name": "Duke Energy Florida LLC",
        "state": "FL",
        "regulatory_jurisdiction": "state_puc",
        "market_structure": "regulated_vertical",
        "input_tier": "TIER_2_PEAK_KW",
    },
    {
        "eia_id": "5419",
        "name": "Duke Energy Indiana LLC",
        "state": "IN",
        "regulatory_jurisdiction": "state_puc",
        "market_structure": "regulated_vertical",
        "input_tier": "TIER_2_PEAK_KW",
    },
    {
        "eia_id": "5420",
        "name": "Duke Energy Ohio Inc",
        "state": "OH",
        "regulatory_jurisdiction": "state_puc",
        "market_structure": "regulated_with_choice",
        "input_tier": "TIER_2_PEAK_KW",
    },
    {
        "eia_id": "5421",
        "name": "Duke Energy Kentucky Inc",
        "state": "KY",
        "regulatory_jurisdiction": "state_puc",
        "market_structure": "regulated_vertical",
        "input_tier": "TIER_2_PEAK_KW",
    },
    # Texas (deregulated TDSP)
    {
        "eia_id": "3672",
        "name": "CenterPoint Energy Houston Electric LLC",
        "state": "TX",
        "regulatory_jurisdiction": "state_puc",
        "market_structure": "deregulated_delivery_only",
        "input_tier": "TIER_2_PEAK_KW",
    },
    {
        "eia_id": "14469",
        "name": "AEP Texas Central Co",
        "state": "TX",
        "regulatory_jurisdiction": "state_puc",
        "market_structure": "deregulated_delivery_only",
        "input_tier": "TIER_2_PEAK_KW",
    },
    {
        "eia_id": "14470",
        "name": "AEP Texas North Co",
        "state": "TX",
        "regulatory_jurisdiction": "state_puc",
        "market_structure": "deregulated_delivery_only",
        "input_tier": "TIER_2_PEAK_KW",
    },
    {
        "eia_id": "40434",
        "name": "Sharyland Utilities LLC",
        "state": "TX",
        "regulatory_jurisdiction": "state_puc",
        "market_structure": "deregulated_delivery_only",
        "input_tier": "TIER_2_PEAK_KW",
    },
    # Midwest / Central
    {
        "eia_id": "1",
        "name": "AmerenIllinois Co",
        "state": "IL",
        "regulatory_jurisdiction": "state_puc",
        "market_structure": "regulated_with_choice",
        "input_tier": "TIER_2_PEAK_KW",
    },
    {
        "eia_id": "2",
        "name": "AmerenMissouri",
        "state": "MO",
        "regulatory_jurisdiction": "state_puc",
        "market_structure": "regulated_vertical",
        "input_tier": "TIER_2_PEAK_KW",
    },
    {
        "eia_id": "3",
        "name": "Commonwealth Edison Co",
        "state": "IL",
        "regulatory_jurisdiction": "state_puc",
        "market_structure": "regulated_with_choice",
        "input_tier": "TIER_2_PEAK_KW",
    },
    {
        "eia_id": "4",
        "name": "Northern States Power Co MN",
        "state": "MN",
        "regulatory_jurisdiction": "state_puc",
        "market_structure": "regulated_vertical",
        "input_tier": "TIER_2_PEAK_KW",
    },
    {
        "eia_id": "5",
        "name": "Xcel Energy - Public Service of Colorado",
        "state": "CO",
        "regulatory_jurisdiction": "state_puc",
        "market_structure": "regulated_vertical",
        "input_tier": "TIER_2_PEAK_KW",
    },
    {
        "eia_id": "6",
        "name": "Southwestern Public Service Co",
        "state": "TX",
        "regulatory_jurisdiction": "state_puc",
        "market_structure": "regulated_vertical",
        "input_tier": "TIER_2_PEAK_KW",
    },
    # Ohio / Pennsylvania
    {
        "eia_id": "7",
        "name": "Ohio Edison Co",
        "state": "OH",
        "regulatory_jurisdiction": "state_puc",
        "market_structure": "regulated_with_choice",
        "input_tier": "TIER_2_PEAK_KW",
    },
    {
        "eia_id": "8",
        "name": "The Illuminating Co",
        "state": "OH",
        "regulatory_jurisdiction": "state_puc",
        "market_structure": "regulated_with_choice",
        "input_tier": "TIER_2_PEAK_KW",
    },
    {
        "eia_id": "9",
        "name": "Toledo Edison Co",
        "state": "OH",
        "regulatory_jurisdiction": "state_puc",
        "market_structure": "regulated_with_choice",
        "input_tier": "TIER_2_PEAK_KW",
    },
    {
        "eia_id": "10",
        "name": "Pennsylvania Electric Co",
        "state": "PA",
        "regulatory_jurisdiction": "state_puc",
        "market_structure": "regulated_with_choice",
        "input_tier": "TIER_2_PEAK_KW",
    },
    {
        "eia_id": "11",
        "name": "West Penn Power Co",
        "state": "PA",
        "regulatory_jurisdiction": "state_puc",
        "market_structure": "regulated_with_choice",
        "input_tier": "TIER_2_PEAK_KW",
    },
    {
        "eia_id": "12",
        "name": "Penn Power",
        "state": "PA",
        "regulatory_jurisdiction": "state_puc",
        "market_structure": "regulated_with_choice",
        "input_tier": "TIER_2_PEAK_KW",
    },
    {
        "eia_id": "13",
        "name": "PECO Energy Co",
        "state": "PA",
        "regulatory_jurisdiction": "state_puc",
        "market_structure": "regulated_with_choice",
        "input_tier": "TIER_2_PEAK_KW",
    },
    {
        "eia_id": "14",
        "name": "PPL Electric Utilities Corp",
        "state": "PA",
        "regulatory_jurisdiction": "state_puc",
        "market_structure": "regulated_with_choice",
        "input_tier": "TIER_2_PEAK_KW",
    },
    # Mid-Atlantic / Northeast
    {
        "eia_id": "15",
        "name": "Baltimore Gas & Electric Co",
        "state": "MD",
        "regulatory_jurisdiction": "state_puc",
        "market_structure": "regulated_with_choice",
        "input_tier": "TIER_2_PEAK_KW",
    },
    {
        "eia_id": "16",
        "name": "Pepco Holdings - Potomac Electric Power",
        "state": "MD",
        "regulatory_jurisdiction": "state_puc",
        "market_structure": "regulated_with_choice",
        "input_tier": "TIER_2_PEAK_KW",
    },
    {
        "eia_id": "17",
        "name": "Jersey Central Power & Light Co",
        "state": "NJ",
        "regulatory_jurisdiction": "state_puc",
        "market_structure": "regulated_with_choice",
        "input_tier": "TIER_2_PEAK_KW",
    },
    {
        "eia_id": "18",
        "name": "Public Service Electric & Gas Co",
        "state": "NJ",
        "regulatory_jurisdiction": "state_puc",
        "market_structure": "regulated_with_choice",
        "input_tier": "TIER_2_PEAK_KW",
    },
    {
        "eia_id": "19",
        "name": "Consolidated Edison Co of New York Inc",
        "state": "NY",
        "regulatory_jurisdiction": "state_puc",
        "market_structure": "regulated_with_choice",
        "input_tier": "TIER_2_PEAK_KW",
    },
    {
        "eia_id": "20",
        "name": "National Grid USA - Niagara Mohawk Power Corp",
        "state": "NY",
        "regulatory_jurisdiction": "state_puc",
        "market_structure": "regulated_with_choice",
        "input_tier": "TIER_2_PEAK_KW",
    },
    {
        "eia_id": "21",
        "name": "New England Electric System",
        "state": "MA",
        "regulatory_jurisdiction": "state_puc",
        "market_structure": "regulated_with_choice",
        "input_tier": "TIER_2_PEAK_KW",
    },
    {
        "eia_id": "22",
        "name": "Eversource Energy - Connecticut Light & Power",
        "state": "CT",
        "regulatory_jurisdiction": "state_puc",
        "market_structure": "regulated_with_choice",
        "input_tier": "TIER_2_PEAK_KW",
    },
    # Southwest / Mountain West
    {
        "eia_id": "23",
        "name": "Arizona Public Service Co",
        "state": "AZ",
        "regulatory_jurisdiction": "state_puc",
        "market_structure": "regulated_vertical",
        "input_tier": "TIER_2_PEAK_KW",
    },
    {
        "eia_id": "24",
        "name": "Tucson Electric Power Co",
        "state": "AZ",
        "regulatory_jurisdiction": "state_puc",
        "market_structure": "regulated_vertical",
        "input_tier": "TIER_2_PEAK_KW",
    },
    {
        "eia_id": "25",
        "name": "Nevada Power Co",
        "state": "NV",
        "regulatory_jurisdiction": "state_puc",
        "market_structure": "regulated_vertical",
        "input_tier": "TIER_2_PEAK_KW",
    },
    {
        "eia_id": "26",
        "name": "Sierra Pacific Power Co",
        "state": "NV",
        "regulatory_jurisdiction": "state_puc",
        "market_structure": "regulated_vertical",
        "input_tier": "TIER_2_PEAK_KW",
    },
    {
        "eia_id": "27",
        "name": "PNM Resources - Public Service Co of New Mexico",
        "state": "NM",
        "regulatory_jurisdiction": "state_puc",
        "market_structure": "regulated_vertical",
        "input_tier": "TIER_2_PEAK_KW",
    },
    {
        "eia_id": "28",
        "name": "Rocky Mountain Power (PacifiCorp)",
        "state": "UT",
        "regulatory_jurisdiction": "state_puc",
        "market_structure": "regulated_vertical",
        "input_tier": "TIER_2_PEAK_KW",
    },
    # California
    {
        "eia_id": "29",
        "name": "Pacific Gas & Electric Co",
        "state": "CA",
        "regulatory_jurisdiction": "state_puc",
        "market_structure": "regulated_with_choice",
        "input_tier": "TIER_1_8760",
    },
    {
        "eia_id": "30",
        "name": "Southern California Edison Co",
        "state": "CA",
        "regulatory_jurisdiction": "state_puc",
        "market_structure": "regulated_with_choice",
        "input_tier": "TIER_1_8760",
    },
    {
        "eia_id": "31",
        "name": "San Diego Gas & Electric Co",
        "state": "CA",
        "regulatory_jurisdiction": "state_puc",
        "market_structure": "regulated_with_choice",
        "input_tier": "TIER_1_8760",
    },
    # Pacific Northwest
    {
        "eia_id": "32",
        "name": "Portland General Electric Co",
        "state": "OR",
        "regulatory_jurisdiction": "state_puc",
        "market_structure": "regulated_vertical",
        "input_tier": "TIER_2_PEAK_KW",
    },
    {
        "eia_id": "33",
        "name": "Puget Sound Energy Inc",
        "state": "WA",
        "regulatory_jurisdiction": "state_puc",
        "market_structure": "regulated_vertical",
        "input_tier": "TIER_2_PEAK_KW",
    },
    # Virginia / Mid-South
    {
        "eia_id": "34",
        "name": "Virginia Electric & Power Co (Dominion)",
        "state": "VA",
        "regulatory_jurisdiction": "state_puc",
        "market_structure": "regulated_vertical",
        "input_tier": "TIER_2_PEAK_KW",
    },
    {
        "eia_id": "35",
        "name": "Appalachian Power Co (AEP)",
        "state": "VA",
        "regulatory_jurisdiction": "state_puc",
        "market_structure": "regulated_vertical",
        "input_tier": "TIER_2_PEAK_KW",
    },
    {
        "eia_id": "36",
        "name": "Kentucky Utilities Co",
        "state": "KY",
        "regulatory_jurisdiction": "state_puc",
        "market_structure": "regulated_vertical",
        "input_tier": "TIER_2_PEAK_KW",
    },
    {
        "eia_id": "37",
        "name": "Louisville Gas & Electric Co",
        "state": "KY",
        "regulatory_jurisdiction": "state_puc",
        "market_structure": "regulated_vertical",
        "input_tier": "TIER_2_PEAK_KW",
    },
    {
        "eia_id": "38",
        "name": "Tennessee Valley Authority",
        "state": "TN",
        "regulatory_jurisdiction": "ferc",
        "market_structure": "regulated_vertical",
        "input_tier": "TIER_2_PEAK_KW",
    },
    {
        "eia_id": "39",
        "name": "Indianapolis Power & Light Co (AES)",
        "state": "IN",
        "regulatory_jurisdiction": "state_puc",
        "market_structure": "regulated_vertical",
        "input_tier": "TIER_2_PEAK_KW",
    },
    {
        "eia_id": "40",
        "name": "Indiana Michigan Power Co (AEP)",
        "state": "IN",
        "regulatory_jurisdiction": "state_puc",
        "market_structure": "regulated_vertical",
        "input_tier": "TIER_2_PEAK_KW",
    },
    # Michigan
    {
        "eia_id": "41",
        "name": "Consumers Energy Co",
        "state": "MI",
        "regulatory_jurisdiction": "state_puc",
        "market_structure": "regulated_with_choice",
        "input_tier": "TIER_2_PEAK_KW",
    },
    {
        "eia_id": "42",
        "name": "The Detroit Edison Co (DTE)",
        "state": "MI",
        "regulatory_jurisdiction": "state_puc",
        "market_structure": "regulated_with_choice",
        "input_tier": "TIER_2_PEAK_KW",
    },
    # Wisconsin / Iowa / Kansas / Nebraska / Dakotas
    {
        "eia_id": "43",
        "name": "Wisconsin Electric Power Co",
        "state": "WI",
        "regulatory_jurisdiction": "state_puc",
        "market_structure": "regulated_vertical",
        "input_tier": "TIER_2_PEAK_KW",
    },
    {
        "eia_id": "44",
        "name": "MidAmerican Energy Co",
        "state": "IA",
        "regulatory_jurisdiction": "state_puc",
        "market_structure": "regulated_vertical",
        "input_tier": "TIER_2_PEAK_KW",
    },
    {
        "eia_id": "45",
        "name": "Kansas City Power & Light Co",
        "state": "MO",
        "regulatory_jurisdiction": "state_puc",
        "market_structure": "regulated_vertical",
        "input_tier": "TIER_2_PEAK_KW",
    },
    {
        "eia_id": "46",
        "name": "Evergy Kansas Central Inc",
        "state": "KS",
        "regulatory_jurisdiction": "state_puc",
        "market_structure": "regulated_vertical",
        "input_tier": "TIER_2_PEAK_KW",
    },
    {
        "eia_id": "47",
        "name": "Oklahoma Gas & Electric Co",
        "state": "OK",
        "regulatory_jurisdiction": "state_puc",
        "market_structure": "regulated_vertical",
        "input_tier": "TIER_2_PEAK_KW",
    },
    {
        "eia_id": "48",
        "name": "Public Service Co of Oklahoma (AEP)",
        "state": "OK",
        "regulatory_jurisdiction": "state_puc",
        "market_structure": "regulated_vertical",
        "input_tier": "TIER_2_PEAK_KW",
    },
    # Mountain / Alaska / Hawaii
    {
        "eia_id": "49",
        "name": "Idaho Power Co",
        "state": "ID",
        "regulatory_jurisdiction": "state_puc",
        "market_structure": "regulated_vertical",
        "input_tier": "TIER_2_PEAK_KW",
    },
    {
        "eia_id": "50",
        "name": "Montana-Dakota Utilities Co",
        "state": "MT",
        "regulatory_jurisdiction": "state_puc",
        "market_structure": "regulated_vertical",
        "input_tier": "TIER_2_PEAK_KW",
    },
    {
        "eia_id": "51",
        "name": "Black Hills Power Inc",
        "state": "SD",
        "regulatory_jurisdiction": "state_puc",
        "market_structure": "regulated_vertical",
        "input_tier": "TIER_2_PEAK_KW",
    },
    {
        "eia_id": "52",
        "name": "Northern Electric Co-op",
        "state": "ND",
        "regulatory_jurisdiction": "state_puc",
        "market_structure": "cooperative",
        "input_tier": "TIER_3_VOLUMETRIC",
    },
    {
        "eia_id": "53",
        "name": "West Virginia American Water / Mon Power",
        "state": "WV",
        "regulatory_jurisdiction": "state_puc",
        "market_structure": "regulated_vertical",
        "input_tier": "TIER_2_PEAK_KW",
    },
    {
        "eia_id": "54",
        "name": "Hawaiian Electric Co Inc",
        "state": "HI",
        "regulatory_jurisdiction": "state_puc",
        "market_structure": "regulated_vertical",
        "input_tier": "TIER_1_8760",
    },
]


# ---------------------------------------------------------------------------
# State bounding boxes  (lat_min, lat_max, lng_min, lng_max)
# Used to generate plausible store lat/lng in seed mode.
# ---------------------------------------------------------------------------

STATE_BOUNDS: dict[str, tuple[float, float, float, float]] = {
    "AL": (30.20, 35.01, -88.47, -84.89),
    "AR": (33.00, 36.50, -94.62, -89.64),
    "AZ": (31.33, 37.00, -114.82, -109.04),
    "CA": (32.53, 42.01, -124.41, -114.13),
    "CO": (36.99, 41.00, -109.05, -102.04),
    "CT": (40.95, 42.05, -73.73, -71.79),
    "DC": (38.79, 38.99, -77.12, -76.91),
    "DE": (38.45, 39.84, -75.79, -75.05),
    "FL": (24.52, 31.00, -87.63, -80.03),
    "GA": (30.36, 35.00, -85.61, -80.84),
    "HI": (18.91, 22.24, -160.24, -154.81),
    "IA": (40.38, 43.50, -96.64, -90.14),
    "ID": (41.99, 49.00, -117.24, -111.04),
    "IL": (36.97, 42.51, -91.51, -87.02),
    "IN": (37.77, 41.76, -88.10, -84.78),
    "KS": (36.99, 40.00, -102.05, -94.59),
    "KY": (36.50, 39.15, -89.57, -81.96),
    "LA": (28.93, 33.02, -94.04, -88.82),
    "MA": (41.24, 42.89, -73.51, -69.93),
    "MD": (37.91, 39.72, -79.49, -75.05),
    "ME": (43.06, 47.47, -71.08, -66.95),
    "MI": (41.70, 48.19, -90.42, -82.41),
    "MN": (43.50, 49.38, -97.24, -89.49),
    "MO": (36.00, 40.61, -95.77, -89.10),
    "MS": (30.17, 35.01, -91.65, -88.10),
    "MT": (44.36, 49.00, -116.05, -104.04),
    "NC": (33.84, 36.59, -84.32, -75.46),
    "ND": (45.94, 49.00, -104.05, -96.55),
    "NE": (40.00, 43.00, -104.05, -95.31),
    "NH": (42.70, 45.31, -72.56, -70.61),
    "NJ": (38.93, 41.36, -75.56, -73.89),
    "NM": (31.33, 37.00, -109.05, -103.00),
    "NV": (35.00, 42.00, -120.00, -114.04),
    "NY": (40.50, 45.02, -79.76, -71.86),
    "OH": (38.40, 42.00, -84.82, -80.52),
    "OK": (33.62, 37.00, -103.00, -94.43),
    "OR": (41.99, 46.26, -124.57, -116.46),
    "PA": (39.72, 42.27, -80.52, -74.69),
    "RI": (41.15, 42.02, -71.91, -71.12),
    "SC": (32.04, 35.22, -83.35, -78.54),
    "SD": (42.48, 45.95, -104.06, -96.44),
    "TN": (34.98, 36.68, -90.31, -81.65),
    "TX": (25.84, 36.50, -106.65, -93.51),
    "UT": (36.99, 42.00, -114.05, -109.04),
    "VA": (36.54, 39.47, -83.68, -75.24),
    "VT": (42.73, 45.02, -73.44, -71.50),
    "WA": (45.54, 49.00, -124.73, -116.92),
    "WI": (42.49, 47.08, -92.89, -86.25),
    "WV": (37.20, 40.64, -82.64, -77.72),
    "WY": (40.99, 45.01, -111.05, -104.05),
    "AK": (55.00, 71.38, -168.00, -129.99),
    "PR": (17.91, 18.52, -67.24, -65.59),
}

# ---------------------------------------------------------------------------
# Approximate Walmart + Sam's Club store counts by state
# Source: Walmart 2023 Annual Report / public store-finder data
# ---------------------------------------------------------------------------

WALMART_STORE_COUNTS: dict[str, int] = {
    "TX": 591,
    "FL": 345,
    "CA": 294,
    "NC": 218,
    "OH": 225,
    "GA": 196,
    "PA": 181,
    "IL": 180,
    "TN": 175,
    "NY": 159,
    "MO": 156,
    "VA": 154,
    "AL": 151,
    "MS": 140,
    "AR": 136,
    "SC": 126,
    "IN": 120,
    "MI": 118,
    "KY": 118,
    "LA": 114,
    "OK": 112,
    "AZ": 109,
    "WI": 97,
    "MN": 87,
    "KS": 81,
    "NJ": 79,
    "WA": 77,
    "CO": 76,
    "IA": 73,
    "NE": 67,
    "MD": 65,
    "CT": 62,
    "WV": 55,
    "NM": 52,
    "ID": 46,
    "UT": 45,
    "MT": 38,
    "SD": 37,
    "ND": 34,
    "OR": 33,
    "NV": 33,
    "ME": 28,
    "NH": 27,
    "VT": 14,
    "WY": 14,
    "AK": 8,
    "HI": 7,
    "DE": 10,
    "RI": 9,
    "DC": 3,
    "PR": 21,
}

SAMSCLUB_STORE_COUNTS: dict[str, int] = {
    "TX": 83,
    "FL": 47,
    "CA": 44,
    "OH": 31,
    "GA": 28,
    "NC": 27,
    "PA": 27,
    "IL": 26,
    "NY": 24,
    "TN": 23,
    "VA": 22,
    "MI": 21,
    "MO": 21,
    "IN": 20,
    "AL": 19,
    "SC": 18,
    "KY": 17,
    "MS": 15,
    "LA": 15,
    "AR": 14,
    "OK": 13,
    "AZ": 13,
    "WI": 13,
    "MN": 12,
    "KS": 11,
    "NJ": 11,
    "CO": 10,
    "IA": 9,
    "MD": 9,
    "WA": 9,
    "NE": 8,
    "CT": 7,
    "WV": 6,
    "NM": 6,
    "UT": 6,
    "ID": 5,
    "NV": 5,
    "OR": 4,
    "MT": 3,
    "SD": 3,
    "ND": 2,
    "ME": 2,
    "NH": 3,
    "WY": 2,
    "AK": 1,
    "HI": 1,
    "DE": 2,
    "RI": 1,
    "DC": 0,
    "PR": 4,
}

# ---------------------------------------------------------------------------
# Primary utility mapping: state → list of (eia_id, fraction_of_state)
# Fractions are approximate; used to probabilistically assign utility_eia_id
# to seed-mode stores.  For v0 reference utilities, assignments are exact.
# ---------------------------------------------------------------------------

STATE_PRIMARY_UTILITIES: dict[str, list[tuple[str, float]]] = {
    "AR": [("6452", 0.65), ("6454", 0.20), ("37", 0.15)],  # Entergy AR dominant
    "NC": [("5416", 0.55), ("5417", 0.40), ("35", 0.05)],  # Duke dominant
    "SC": [("5416", 0.45), ("5417", 0.40), ("34", 0.15)],
    "TX": [
        ("40229", 0.35),
        ("3672", 0.20),
        ("14469", 0.15),  # Oncor, CenterPoint, AEP TX
        ("6454", 0.15),
        ("6", 0.10),
        ("14470", 0.05),
    ],
    "GA": [("7140", 0.80), ("35", 0.10), ("38", 0.10)],  # Georgia Power dominant
    "FL": [
        ("6455", 0.50),
        ("5418", 0.20),
        ("12341", 0.10),  # FPL, Duke FL
        ("15", 0.10),
        ("25", 0.10),
    ],
    "AL": [("12341", 0.75), ("38", 0.20), ("11249", 0.05)],
    "MS": [("18195", 0.40), ("11249", 0.35), ("38", 0.25)],
    "LA": [("12345", 0.50), ("6453", 0.20), ("6454", 0.10), ("6452", 0.20)],
    "TN": [("38", 0.95), ("37", 0.05)],
    "KY": [("36", 0.35), ("37", 0.35), ("38", 0.20), ("35", 0.10)],
    "VA": [("34", 0.70), ("35", 0.25), ("38", 0.05)],
    "WV": [("53", 0.60), ("35", 0.40)],
    "OH": [("7", 0.30), ("8", 0.15), ("9", 0.15), ("5420", 0.40)],
    "PA": [("13", 0.25), ("14", 0.30), ("10", 0.20), ("11", 0.15), ("12", 0.10)],
    "NJ": [("18", 0.55), ("17", 0.45)],
    "MD": [("15", 0.60), ("16", 0.40)],
    "DC": [("16", 1.0)],
    "DE": [("16", 1.0)],
    "NY": [("19", 0.45), ("20", 0.35), ("21", 0.20)],
    "CT": [("22", 1.0)],
    "MA": [("21", 1.0)],
    "RI": [("21", 1.0)],
    "NH": [("21", 1.0)],
    "ME": [("21", 1.0)],
    "VT": [("21", 1.0)],
    "IL": [("3", 0.55), ("1", 0.45)],
    "MO": [("2", 0.55), ("45", 0.30), ("6452", 0.15)],
    "MN": [("4", 1.0)],
    "CO": [("5", 0.90), ("28", 0.10)],
    "TX_": [("6", 0.90), ("27", 0.10)],  # NM border TX area
    "KS": [("46", 0.65), ("45", 0.35)],
    "NE": [("44", 0.80), ("45", 0.20)],
    "IA": [("44", 0.75), ("4", 0.25)],
    "WI": [("43", 0.70), ("4", 0.30)],
    "MI": [("41", 0.55), ("42", 0.45)],
    "IN": [("39", 0.35), ("40", 0.35), ("5419", 0.30)],
    "OK": [("47", 0.55), ("48", 0.45)],
    "NM": [("27", 0.80), ("6", 0.20)],
    "AZ": [("23", 0.75), ("24", 0.25)],
    "NV": [("25", 0.65), ("26", 0.35)],
    "UT": [("28", 1.0)],
    "ID": [("49", 0.65), ("28", 0.35)],
    "MT": [("50", 0.60), ("28", 0.40)],
    "WY": [("28", 0.70), ("50", 0.30)],
    "SD": [("51", 0.45), ("44", 0.30), ("52", 0.25)],
    "ND": [("52", 0.50), ("50", 0.30), ("51", 0.20)],
    "CA": [("29", 0.40), ("30", 0.45), ("31", 0.15)],
    "OR": [("32", 0.60), ("28", 0.40)],
    "WA": [("33", 0.80), ("28", 0.20)],
    "AK": [("50", 1.0)],
    "HI": [("54", 1.0)],
    "PR": [("55", 1.0)],
}
